/**
 * @copyright   2016-2018, Miles Johnson
 * @license     https://opensource.org/licenses/MIT
 */

import React from 'react';
import PropTypes from 'prop-types';
import Element from './Element';
import Parser from './Parser';

export interface MarkupProps {
  /** Content with HTML to safely render. */
  content?: string;
  /** Disable the conversion of new lines to `<br />` elements. */
  disableLineBreaks?: boolean;
  /** Disable the HTML element whitelist. */
  disableWhitelist?: boolean;
  /** Content to render when the `content` prop is empty. */
  emptyContent?: React.ReactNode;
  /** Strip all HTML while rendering. */
  noHtml?: boolean;
  /** Strip all HTML except HTML generated by matchers while rendering. */
  noHtmlExceptMatchers?: boolean;
  /** @ignore Pre-parsed content to render. */
  parsedContent?: React.ReactNode;
  /** HTML element or React fragment to wrap content with. */
  tagName?: string;
}

export default class Markup extends React.PureComponent<MarkupProps> {
  static propTypes = {
    content: PropTypes.string,
    disableLineBreaks: PropTypes.bool,
    disableWhitelist: PropTypes.bool,
    emptyContent: PropTypes.node,
    noHtml: PropTypes.bool,
    noHtmlExceptMatchers: PropTypes.bool,
    parsedContent: PropTypes.node,
    tagName: PropTypes.oneOf(['span', 'div', 'p', 'fragment']),
  };

  static defaultProps = {
    content: '',
    disableLineBreaks: false,
    disableWhitelist: false,
    emptyContent: null,
    noHtml: false,
    noHtmlExceptMatchers: false,
    parsedContent: null,
    tagName: 'div',
  };

  getContent(): React.ReactNode {
    const {
      content = '',
      noHtml,
      noHtmlExceptMatchers,
      disableLineBreaks,
      disableWhitelist,
      emptyContent,
      parsedContent,
    } = this.props;

    if (parsedContent) {
      return parsedContent;
    }

    const markup = new Parser(content || '', {
      disableLineBreaks,
      disableWhitelist,
      noHtml,
      noHtmlExceptMatchers,
    }).parse();

    return markup.length ? markup : emptyContent;
  }

  render() {
    const content = this.getContent();
    const tag = this.props.tagName;

    return tag === 'fragment' ? (
      <React.Fragment>{content}</React.Fragment>
    ) : (
      <Element tagName={tag || 'div'}>{content}</Element>
    );
  }
}
